version: "3"

services:
  linebot-gpt:
    image: us-central1-docker.pkg.dev/jidou-ai/local/linebot-gpt:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - N8N_API_KEY=wPMbXUcN74o10qXj_o-LYQ
      - SYSTEM_MESSAGE=你是一個助理機器人，請根據使用者的回覆回答問題
      - LINE_CHANNEL_ACCESS_TOKEN=5CsHfuM8szSsNpAGef/+M7ehTUWaM11+Xsf0OxjjrzzdWwe1TE+UwbCxGmTGqtEHHrhriGmZhmqC/zGWnfmCv+3rjztINdb564KfQrVhO1lwFH81ASm/Srei+In22VWi0UdOFKR0+dKpuA30ANGWZQdB04t89/1O/w1cDnyilFU=
      - LINE_CHANNEL_SECRET=22ed91dfd06d5646ffb2d7de6173c0cb
      - OPENAI_API_KEY=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
      - OPENAI_MODEL_ENGINE=gpt-4-0125-preview
      - PSQL_DB_HOST=aws-0-us-east-1.pooler.supabase.com
      - PSQL_DB_DBNAME=postgres
      - PSQL_DB_USER=postgres.juatyfoqraonbpzgkpdp
      - PSQL_DB_PWD=eBq.8b7teW4au6
      - PSQL_DB_PORT=5432
